services:
  backend:
    build: ./backend
    container_name: pizzaria-backend
    restart: unless-stopped
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: pizzaria-frontend
    depends_on:
      - backend
    ports:
      - "${APP_PORT:-8080}:80"
    restart: unless-stopped